@startuml
'https://plantuml.com/sequence-diagram

autonumber

Alice -> Bob: Authentication Request
Pau -> Alice: Envio de mensaje

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml